language: emacs-lisp

env:
  matrix:
    - EMACS=emacs24
    - EMACS=emacs-snapshot
  global:
    - CASK=${HOME}/.cask/bin/cask

install:
  - sudo add-apt-repository -y ppa:cassou/emacs &&
    sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
  - sudo apt-get update -qq &&
    sudo apt-get install -qq &&
    sudo apt-get install ${EMACS} ${EMACS}-el
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python

script:
  make test
