language: emacs-lisp

sudo: false

env:
  - EMACS=emacs24
  - CASK=${HOME}/.cask/bin/cask

addons:
  apt:
    packages:
      - ${EMACS}

install:
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - ${CASK} install

script:
  - ${EMACS} --version
  - make compile test-lisp test-startup
