language: generic

dist: trusty
sudo: true

# addons:
#   apt:
#     sources:
#       - sourceline: 'ppa:ubuntu-elisp/ppa'
#     packages:
#       - emacs
#       - emacs-snapshot

env:
  global:
    # XXX: see details, etc/NEWS.24
    - NO_BIN_LINK=t
  matrix:
    # - EMACS=emacs
    # - EMACS=emacs-snapshot
    - EMACS=emacs-24.4
    - EMACS=emacs-24.5
    - EMACS=emacs-25.3
    - EMACS=emacs-26.1

matrix:
  allow_failures:
    # Daily Snapshot is not stable release (and other libs may not support)
    # - env: EMACS=emacs-snapshot
    - env: EMACS=emacs-24.4
    - env: EMACS=emacs-24.5

before_install:
  # XXX: see details, etc/PROBLEMS [*** Segfault during 'make']
  - cat /proc/sys/kernel/randomize_va_space
  - sudo bash -c "echo 0 > /proc/sys/kernel/randomize_va_space"

  - make -f makefiles/emacs.mk EMACS=${EMACS} PREFIX=${HOME}/.local/${EMACS}
  - ls -lh ${HOME}/.local/${EMACS}/bin
  - export PATH=${HOME}/.local/${EMACS}/bin:${PATH}
  - ${EMACS} --version
    
install:
  - make package-install

script:
  - make compile test-lisp
  - make test-startup
