language: emacs-lisp

sudo: required

env:
  matrix:
    - EMACS=emacs24
    - EMACS=emacs-snapshot
  global:
    - CASK=${HOME}/.cask/bin/cask

matrix:
  allow_failures:
    - EMACS: emacs-snapshot

cache:
  directories:
    - ${HOME}/.emacs.d/.cask
    - ${HOME}/.emacs.d/elpa

install:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
  - sudo apt-get update -qq
  - sudo apt-get install ${EMACS}
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - ${CASK} install

script:
  - ${EMACS} --version
  - make compile test-lisp test-startup
