language: generic

sudo: required
dist: trusty

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-elisp/ppa'
    packages:
      - emacs
      - emacs-snapshot

env:
  - EMACS=emacs
  - EMACS=emacs-snapshot

allow_failures:
  # Emacs Daily Snapshot is not stable release.
  - env: EMACS=emacs-snapshot

install:
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH=$PATH:$HOME/.cask/bin
  - cask install

script:
  - $EMACS --version
  - make compile test-lisp
  - make test-startup
