language: emacs-lisp

sudo: false

addons:
  apt:
    packages:
      - emacs24

install:
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH=$PATH:$HOME/.cask/bin
  - cask install

script:
  - emacs --version
  - make compile test-lisp test-startup
