language: generic

dist: trusty
sudo: true

# addons:
#   apt:
#     sources:
#       - sourceline: 'ppa:ubuntu-elisp/ppa'
#     packages:
#       - emacs
#       - emacs-snapshot

git:
  submodules: false

env:
  matrix:
    - EMACS=emacs-25.3
    - EMACS=emacs-26.3

matrix:
  allow_failures:
    # FIXME: elpa.gnu.org:443 (bad-signature "archive-contents.sig")
    - env: EMACS=emacs-25.3

before_install:
  # https://gist.github.com/iedemam/9830045
  - sed -i 's/git@\(gist.\|\)github.com:/git:\/\/github.com\//' .gitmodules
  - git submodule update --init share/makefiles

  # XXX: see details, etc/PROBLEMS [*** Segfault during 'make']
  - sudo sysctl kernel.randomize_va_space
  - sudo sysctl -w kernel.randomize_va_space=0

  - make -f share/makefiles/emacs.mk EMACS=${EMACS} PREFIX=${HOME}/.local/${EMACS}
  - ls -lh "${HOME}/.local/${EMACS}/bin"
  - export PATH="${HOME}/.local/${EMACS}/bin":${PATH}
  - ${EMACS} --version
    
install:
  - make package-install

script:
  - make compile test-lisp
  - make test-startup
