name: CI

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          #- macos-latest
        emacs_version:
          - 28.2
          - 29.4
          - 30.1
        #experimental: [false]
        include:
          - emacs_version: snapshot
            allow_failure: "true"
            #experimental: true
    runs-on: ${{ matrix.os }}
    #continue-on-error: ${{ matrix.experimental }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup Emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - name: Install Packages
      run: make package-install
    - name: Byte Compiling
      run: make compile
      continue-on-error: true
    - name: Testing
      run: make test
      continue-on-error: true
    - name: Startup
      run: make test-startup
      continue-on-error: ${{ matrix.allow_failure == 'true' }}
