name: CI

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        emacs_version:
          - 26.1
          - 27.1
          - 28.1
          - snapshot
        include:
          - os: macos-latest
            emacs_version: 28.2

    steps:
    - uses: actions/checkout@v2
      with:
        submodule: recursive

    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - name: Check Emacs version
      run: emacs --version

    - name: Install Packages
      run: make package-install

    - name: Byte Compiling
      run: make compile

    - name: Testing
      run: make test

    - name: Startup
      run: make test-startup
