name: CI

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
      - 'memo/*'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # NOTE: macos supports emacs-28.1 or later
          # - macos-latest
        emacs-version:
          - 28.2
          - 29.4
          - 30.1
        experimental: [false]
        # FIXME: Error when evaluating 'runs-on' for job 'test'. Unexpected value ''
        # https://github.com/kosh04/.emacs.d/actions/runs/15479192927
        # include:
        #   - emacs-version: snapshot
        #     experimental: true
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs-version }}
    - run: make package-install
    - run: make compile
    - run: make test
    - run: make test-startup
